# PeerPrep Docker Compose Configuration
# TODO: when deploying to production, switch to using images from Docker Hub -> using 'image' and 'pull_policy' and remove 'build' sections
services:
  # Frontend Next.js Application
  # Scalable service with port range mapping
  # container_name is omitted for scaling
  # which is important for peerprep where we do matching
  frontend:
    image: honeydews/frontend
    pull_policy: never
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner # Production build target
    ports:
      - "3000-3001:3000" # Port range for scaling (use --scale frontend=N)

  user-service:
    image: foochao/user-service
    pull_policy: never
    build:
      context: ./user-service
      dockerfile: Dockerfile
      # Use the runner stage from the multi-stage Dockerfile (not production)
      target: runner
    ports:
      - "4000:4000" # Expose user-service on port 3001 (matches your app)
    env_file:
      - ./user-service/.env # Environment variables for user-service
  
  # MongoDB Database for User Services
  mongodb-user-services:
    image: mongo:7.0.12
    container_name: peerprep-mongodb-user-services
    volumes:
      - mongodb-data-user-services:/data/db # Persistent data storage
    env_file:
      - ./mongodb/.env # Database credentials
    profiles:
      - localdb # Only runs with --profile localdb

  # MongoDB Web Admin Interface
  mongo-express:
    image: mongo-express:1.0.2
    container_name: peerprep-mongo-express
    ports:
      - "8081:8081" # Web interface on localhost:8081
    env_file:
      - ./mongo-express/.env # Connection settings
    depends_on:
      - mongodb-user-services # Requires MongoDB to be running
    profiles:
      - localdb # Only runs with --profile localdb

# Named volumes for data persistence
volumes:
  mongodb-data-user-services:
