services:
  frontend:
    image: honeydews/frontend
    pull_policy: always
    container_name: peerprep-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"

  mongodb-user-services:
    image: mongo:7.0.12
    container_name: peerprep-mongodb-user-services
    volumes:
      - mongodb-data-user-services:/data/db
    env_file:
      - ./mongodb/.env

  mongo-express:
    image: mongo-express:1.0.2
    container_name: peerprep-mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ./mongo-express/.env
    depends_on:
      - mongodb-user-services

volumes:
  mongodb-data-user-services:
